/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseInfo: typeof import('./src/components/provideCom/coms/baseInfo.vue')['default']
    Btn: typeof import('./src/components/btn.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    Modal: typeof import('./src/components/drawer/modal.vue')['default']
    ProvideCom: typeof import('./src/components/provideCom/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingInfo: typeof import('./src/components/provideCom/coms/settingInfo.vue')['default']
    SettingItem: typeof import('./src/components/provideCom/coms/coms/settingItem.vue')['default']
  }
}
